##1. Fizz Buzz
# Write a program that prints the numbers from 1 to 100. 
# But for multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". 
# For numbers which are multiples of both three and five print "FizzBuzz".

# #define function
def printFizzBUzz(): 
    #loop through all nums
    for num in range(101):
        if num % 3 == 0 and num % 5 == 0:
            print("fizzbuzz")
            continue
        if num % 3 == 0: 
            print("fizz")
            continue
        if num % 5 == 0:
            print ("buzz")
            continue
    
        print(num)
        
printFizzBUzz()


#2. Sum of All Multiples of 3 or 5 below 1000
# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.


def sumOf3or5():

    count = 0
    for num in range(1000): 
        if num % 3 == 0 or num % 5== 0:
            count += num 
        
    print(count)
sumOf3or5()
            

#Fibonacci Sequence
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# def function 

def fibsEven(): 
    a = 0
    b = 1
    total = 0
    while total <= 40000000: 
        a = b
        b = a+b 
        if b % 2 == 0: 
            total += b
    print(total)
print(fibsEven())



